// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjXLk44mia2PlI8ZvYv6EbvblN0snMOCk',
    appId: '1:570655138630:web:9380c45ac55bbaecde7b47',
    messagingSenderId: '570655138630',
    projectId: 'coloro-e4a4b',
    authDomain: 'coloro-e4a4b.firebaseapp.com',
    storageBucket: 'coloro-e4a4b.firebasestorage.app',
    measurementId: 'G-5QD8TH7PQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb61crYCntzNuMfmmHLlkJWbfMEL0hk_8',
    appId: '1:570655138630:android:59cb98d53e5287b7de7b47',
    messagingSenderId: '570655138630',
    projectId: 'coloro-e4a4b',
    storageBucket: 'coloro-e4a4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw0qnruv0xcM0KvVPxOtafVmOtNZUtpzU',
    appId: '1:570655138630:ios:4e613270e381a325de7b47',
    messagingSenderId: '570655138630',
    projectId: 'coloro-e4a4b',
    storageBucket: 'coloro-e4a4b.firebasestorage.app',
    iosBundleId: 'com.megz.coloro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw0qnruv0xcM0KvVPxOtafVmOtNZUtpzU',
    appId: '1:570655138630:ios:4e613270e381a325de7b47',
    messagingSenderId: '570655138630',
    projectId: 'coloro-e4a4b',
    storageBucket: 'coloro-e4a4b.firebasestorage.app',
    iosBundleId: 'com.megz.coloro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjXLk44mia2PlI8ZvYv6EbvblN0snMOCk',
    appId: '1:570655138630:web:323006b6febbb768de7b47',
    messagingSenderId: '570655138630',
    projectId: 'coloro-e4a4b',
    authDomain: 'coloro-e4a4b.firebaseapp.com',
    storageBucket: 'coloro-e4a4b.firebasestorage.app',
    measurementId: 'G-3RCQE0NJEN',
  );
}
