// Generates the whole campaign: level PNGs + assets/levels/levels.json.
// Run with: dart run tool/gen_levels.dart
//
// 300 levels, 4 normal : 1 hard, both tracks ramped easiest → hardest.
// See docs/LEVEL_DESIGN_RULES.md for the design rule this implements.
//
// Difficulty in bottom-drain is NOT just "more colors" — it is:
//   1. VERTICAL CHURN — how often the color changes walking up a column.
//      [A,A,A,B,B,B] needs two bottles in sequence; [A,B,A,B,A,B] forces
//      constant swapping against only 5 slots.
//   2. TRAY SHUFFLE — how far a bottle sits from where it is needed. The
//      player must park bottles in slots and keep one breathing.
// Both ramp with the level number, and every shipped level carries a
// (shuffleWindow, dealSeed) pair proven solvable by the real slot-limited
// solver in BottleFactory.
import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;
import 'dart:typed_data';

import 'package:coloro/data/bottle_factory.dart';
import 'package:coloro/data/quantizer.dart';
import 'package:image/image.dart' as img;

const totalLevels = 300;
const normalCount = 240;
const hardCount = 60;

void main() {
  Directory('assets/levels').createSync(recursive: true);
  for (final f in Directory('assets/levels').listSync()) {
    if (f is File && RegExp(r'/\d+\.(png|jpg)$').hasMatch(f.path)) {
      f.deleteSync();
    }
  }

  final manifest = <String, Map<String, Object>>{};
  var totalAttempts = 0;

  for (var n = 1; n <= totalLevels; n++) {
    final spec = LevelSpec.forLevel(n);
    final built = _buildLevel(spec);
    totalAttempts += built.attempts;

    savePng('$n.png', built.scene.grid);
    manifest['$n.png'] = {
      'name': built.scene.name,
      'gridSize': spec.gridSize,
      'maxColors': built.colorCount,
      'hard': spec.hard,
      // Everything that defines this level's difficulty, spelled out.
      'colors': built.colorCount,
      'cells': spec.gridSize * spec.gridSize,
      'churn': double.parse(built.churn.toStringAsFixed(2)),
      'shuffleWindow': built.shuffleWindow,
      'dealSeed': built.dealSeed,
      'bottles': built.bottleCount,
    };
    if (n % 25 == 0) stdout.writeln('  … level $n');
  }

  final json = const JsonEncoder.withIndent('  ').convert({
    'comment':
        'Generated by tool/gen_levels.dart — 240 normal + 60 hard levels '
            'interleaved 4:1, ramped easy → hard. Every level ships with a '
            'shuffleWindow/dealSeed pair proven solvable by the slot-limited '
            'solver. Do not edit by hand; see docs/LEVEL_DESIGN_RULES.md.',
    'levels': manifest,
  });
  File('assets/levels/levels.json').writeAsStringSync('$json\n');
  stdout.writeln(
      'Generated $totalLevels levels ($totalAttempts solver checks)');
}

// ---------------------------------------------------------------------------
// Per-level difficulty specification
// ---------------------------------------------------------------------------

class LevelSpec {
  const LevelSpec({
    required this.number,
    required this.hard,
    required this.t,
    required this.gridSize,
    required this.colorTarget,
    required this.churn,
    required this.shuffleWindow,
    required this.tier,
  });

  /// Ramps for level [n]. Normal and hard levels ramp on separate tracks.
  factory LevelSpec.forLevel(int n) {
    final hard = n % 5 == 0;
    final double t;
    final int gridSize, colorTarget, shuffleWindow;
    final double churn;
    if (hard) {
      final j = n ~/ 5; // 1..60
      t = (j - 1) / (hardCount - 1);
      gridSize = (20 + t * 20).round();
      colorTarget = (7 + t * 3).round(); // 7 .. 10
      churn = 0.45 + t * 0.25; // busy from the start: 0.45 .. 0.70
      shuffleWindow = (4 + t * 8).round(); // 4 .. 12
    } else {
      final i = n - n ~/ 5; // 1..240
      t = (i - 1) / (normalCount - 1);
      gridSize = (15 + t * 24).round();
      colorTarget = (5 + t * 4).round(); // 5 .. 9
      churn = 0.30 + t * 0.28; // 0.30 .. 0.58
      shuffleWindow = (2 + t * 7).round(); // 2 .. 9
    }
    return LevelSpec(
      number: n,
      hard: hard,
      t: t,
      gridSize: gridSize.clamp(15, 40),
      colorTarget: colorTarget,
      churn: churn,
      shuffleWindow: shuffleWindow,
      tier: t < 0.28 ? 0 : (t < 0.62 ? 1 : 2),
    );
  }

  final int number;
  final bool hard;
  final double t;
  final int gridSize;
  final int colorTarget;

  /// 0..1 — how aggressively the art breaks colors up vertically.
  final double churn;

  /// Target tray displacement (the shipped value may end up lower).
  final int shuffleWindow;

  /// Motif complexity tier: 0 easy, 1 mid, 2 advanced.
  final int tier;
}

class BuiltLevel {
  BuiltLevel({
    required this.scene,
    required this.colorCount,
    required this.churn,
    required this.shuffleWindow,
    required this.dealSeed,
    required this.bottleCount,
    required this.attempts,
  });

  final Scene scene;
  final int colorCount;
  final double churn;
  final int shuffleWindow;
  final int dealSeed;
  final int bottleCount;
  final int attempts;
}

/// Builds a scene, then searches for the strongest tray shuffle the real
/// solver can still beat — falling back through weaker shuffles and then
/// fresh scenes, so every level ships proven-winnable.
BuiltLevel _buildLevel(LevelSpec spec) {
  var attempts = 0;
  for (var sceneTry = 0; sceneTry < 24; sceneTry++) {
    // Ease the colour target only after several scenes have failed — the
    // ceiling is what 5 slots can actually juggle.
    final easedSpec = sceneTry < 12
        ? spec
        : LevelSpec(
            number: spec.number,
            hard: spec.hard,
            t: spec.t,
            gridSize: spec.gridSize,
            colorTarget: math.max(5, spec.colorTarget - (sceneTry - 11)),
            churn: spec.churn,
            shuffleWindow: spec.shuffleWindow,
            tier: spec.tier,
          );
    final scene =
        buildScene(easedSpec, seed: spec.number * 7919 + sceneTry * 104729);
    final grid = quantizeImage(
      img.decodeImage(_encodePng(scene.grid))!,
      gridSize: spec.gridSize,
      maxColors: scene.colorCount,
    );
    if (grid.palette.length < 5) continue;

    final base = BottleFactory.build(grid, seed: spec.number);
    final bottleCount = base.length;

    // Cheap feasibility gate: if the perfectly-sorted deal cannot be won,
    // no shuffle of it can be either — drop the scene immediately.
    attempts++;
    if (!BottleFactory.isDealSolvable(grid, base, maxNodes: 30000)) continue;

    // Strongest shuffle first — that's the interesting one.
    for (var window = spec.shuffleWindow; window >= 1; window--) {
      final tries = window == 1 ? 1 : 3;
      for (var k = 0; k < tries; k++) {
        attempts++;
        final dealSeed = (spec.number * 977 + k * 7919 + window * 31) % 100000;
        final deal = BottleFactory.build(
          grid,
          seed: spec.number,
          shuffleWindow: window,
          dealSeed: dealSeed,
        );
        if (BottleFactory.isDealSolvable(grid, deal, maxNodes: 35000)) {
          return BuiltLevel(
            scene: scene,
            colorCount: grid.palette.length,
            churn: _churnOf(grid.cells, grid.cols, grid.rows),
            shuffleWindow: window,
            dealSeed: dealSeed,
            bottleCount: bottleCount,
            attempts: attempts,
          );
        }
      }
    }
  }
  stderr.writeln('LEVEL ${spec.number}: no solvable scene found!');
  exit(1);
}

/// Fraction of vertical neighbour pairs whose color changes — the real
/// difficulty signal for bottom-drain.
double _churnOf(List<int> cells, int cols, int rows) {
  var changes = 0, pairs = 0;
  for (var x = 0; x < cols; x++) {
    for (var y = 0; y < rows - 1; y++) {
      pairs++;
      if (cells[y * cols + x] != cells[(y + 1) * cols + x]) changes++;
    }
  }
  return pairs == 0 ? 0 : changes / pairs;
}

Uint8List _encodePng(Grid g) {
  final im = img.Image(width: g.n, height: g.n, numChannels: 4);
  for (var y = 0; y < g.n; y++) {
    for (var x = 0; x < g.n; x++) {
      final c = g.at(x, y);
      im.setPixelRgba(x, y, (c >> 16) & 0xFF, (c >> 8) & 0xFF, c & 0xFF, 255);
    }
  }
  return img.encodePng(im);
}

void savePng(String name, Grid g) {
  File('assets/levels/$name').writeAsBytesSync(_encodePng(g));
}

// ---------------------------------------------------------------------------
// Canvas
// ---------------------------------------------------------------------------

class Grid {
  Grid(this.n, int skyColor) : cells = List.filled(n * n, skyColor);

  final int n;
  final List<int> cells;

  void set(int x, int y, int argb) {
    if (x < 0 || y < 0 || x >= n || y >= n) return;
    cells[y * n + x] = argb;
  }

  int at(int x, int y) =>
      (x < 0 || y < 0 || x >= n || y >= n) ? 0 : cells[y * n + x];

  /// Paints [color] wherever [inside] is true, in normalized [-1,1] coords.
  void fill(bool Function(double nx, double ny) inside, int color) {
    for (var y = 0; y < n; y++) {
      for (var x = 0; x < n; x++) {
        final nx = (x + 0.5) / n * 2 - 1;
        final ny = (y + 0.5) / n * 2 - 1;
        if (inside(nx, ny)) set(x, y, color);
      }
    }
  }

  /// Repaints [from] cells as [to] inside an ellipse — used for shading.
  void shade(double cx, double cy, double rx, double ry, int from, int to) {
    for (var y = 0; y < n; y++) {
      for (var x = 0; x < n; x++) {
        final nx = (x + 0.5) / n * 2 - 1;
        final ny = (y + 0.5) / n * 2 - 1;
        final dx = (nx - cx) / rx, dy = (ny - cy) / ry;
        if (dx * dx + dy * dy <= 1 && at(x, y) == from) set(x, y, to);
      }
    }
  }

  /// Outlines every cell of [target] that touches a different color.
  void outline(int target, int color) {
    final snap = List<int>.from(cells);
    int atS(int x, int y) =>
        (x < 0 || y < 0 || x >= n || y >= n) ? target : snap[y * n + x];
    for (var y = 0; y < n; y++) {
      for (var x = 0; x < n; x++) {
        if (atS(x, y) != target) continue;
        if (atS(x - 1, y) != target ||
            atS(x + 1, y) != target ||
            atS(x, y - 1) != target ||
            atS(x, y + 1) != target) {
          set(x, y, color);
        }
      }
    }
  }

  void plus(int x, int y, int color, {int arm = 1}) {
    set(x, y, color);
    for (var k = 1; k <= arm; k++) {
      set(x - k, y, color);
      set(x + k, y, color);
      set(x, y - k, color);
      set(x, y + k, color);
    }
  }

  /// Ring [layer] cells in from the border (0 = outermost).
  void ring(int layer, int color) {
    for (var y = 0; y < n; y++) {
      for (var x = 0; x < n; x++) {
        final r = [x, n - 1 - x, y, n - 1 - y].reduce(math.min);
        if (r == layer) set(x, y, color);
      }
    }
  }

  /// A horizontal band of alternating colors — pure vertical churn.
  void checkerRow(int y, int a, int b, {int period = 1}) {
    for (var x = 0; x < n; x++) {
      set(x, y, (x ~/ period).isEven ? a : b);
    }
  }
}

/// Places a motif inside a sub-region of the grid.
class Zone {
  Zone(this.g, {this.cx = 0, this.cy = 0, this.scale = 1});

  final Grid g;
  final double cx, cy, scale;

  void fill(bool Function(double x, double y) inside, int color) {
    g.fill((nx, ny) => inside((nx - cx) / scale, (ny - cy) / scale), color);
  }
}

// ---------------------------------------------------------------------------
// Color helpers + palettes
// ---------------------------------------------------------------------------

int darken(int c, [double f = 0.68]) {
  int m(int v) => (v * f).round().clamp(0, 255);
  return 0xFF000000 |
      (m(c >> 16 & 0xFF) << 16) |
      (m(c >> 8 & 0xFF) << 8) |
      m(c & 0xFF);
}

int lighten(int c, [double f = 0.42]) {
  int m(int v) => (v + (255 - v) * f).round().clamp(0, 255);
  return 0xFF000000 |
      (m(c >> 16 & 0xFF) << 16) |
      (m(c >> 8 & 0xFF) << 8) |
      m(c & 0xFF);
}

int mixColor(int a, int b, double f) {
  int m(int x, int y) => (x + (y - x) * f).round().clamp(0, 255);
  return 0xFF000000 |
      (m(a >> 16 & 0xFF, b >> 16 & 0xFF) << 16) |
      (m(a >> 8 & 0xFF, b >> 8 & 0xFF) << 8) |
      m(a & 0xFF, b & 0xFF);
}

/// A themed scene palette: a sky graded from top to horizon, ground tones,
/// and accents that are GUARANTEED mutually distinct — anything closer
/// than the quantizer's merge distance would silently collapse the
/// palette and flatten the difficulty.
class Palette {
  Palette(this.name, this.skyTop, this.skyLow, this.ground, this.hueOffset)
      : accents = _separatedAccents(hueOffset, [skyTop, skyLow, ground]);

  final String name;
  final int skyTop;
  final int skyLow;
  final int ground;
  final double hueOffset;
  final List<int> accents;
}

int _hsl(double h, double s, double l) {
  h = (h % 360 + 360) % 360;
  final c = (1 - (2 * l - 1).abs()) * s;
  final x = c * (1 - ((h / 60) % 2 - 1).abs());
  final m = l - c / 2;
  double r = 0, g = 0, b = 0;
  if (h < 60) {
    r = c;
    g = x;
  } else if (h < 120) {
    r = x;
    g = c;
  } else if (h < 180) {
    g = c;
    b = x;
  } else if (h < 240) {
    g = x;
    b = c;
  } else if (h < 300) {
    r = x;
    b = c;
  } else {
    r = c;
    b = x;
  }
  int q(double v) => ((v + m) * 255).round().clamp(0, 255);
  return 0xFF000000 | (q(r) << 16) | (q(g) << 8) | q(b);
}

/// Farthest-point sampling over a wide hue × lightness × saturation grid:
/// repeatedly take the candidate that is furthest from everything already
/// chosen. That extracts the most mutually-distinct palette the metric
/// allows, so accents never collapse during quantization.
List<int> _separatedAccents(double hueOffset, List<int> fixed) {
  final candidates = <int>[];
  for (final l in [0.30, 0.44, 0.58, 0.72, 0.86]) {
    for (final sat in [0.90, 0.55]) {
      for (var k = 0; k < 12; k++) {
        candidates.add(_hsl(hueOffset + k * 30.0, sat, l));
      }
    }
  }
  candidates
    ..add(0xFFFDFEFF)
    ..add(0xFF16161F);

  final kept = <int>[];
  while (kept.length < 14) {
    var best = -1;
    var bestMin = 0.0;
    for (final c in candidates) {
      var minD = double.infinity;
      for (final f in fixed) {
        minD = math.min(minD, _colorDist(f, c));
      }
      for (final k in kept) {
        minD = math.min(minD, _colorDist(k, c));
      }
      if (minD > bestMin) {
        bestMin = minD;
        best = c;
      }
    }
    if (best == -1 || bestMin < _minSeparation) break;
    kept.add(best);
  }
  return kept;
}

/// Comfortably above the runtime quantizer's ~52 merge distance.
const _minSeparation = 56.0;

final palettes = [
  Palette('Night', 0xFF1E1145, 0xFF8B5CF6, 0xFF243B1E, 20),
  Palette('Day', 0xFF1971C2, 0xFFA5D8FF, 0xFF2F9E44, 200),
  Palette('Candy', 0xFFC2255C, 0xFFFFC9DE, 0xFF7048E8, 95),
  Palette('Ocean', 0xFF0B4F6C, 0xFF66D9E8, 0xFFE8C39E, 330),
  Palette('Sunset', 0xFF5F1F6E, 0xFFFFA94D, 0xFF2B3A55, 150),
  Palette('Forest', 0xFF1C7ED6, 0xFFD3F9D8, 0xFF2B8A3E, 45),
  Palette('Space', 0xFF0B0E24, 0xFF5B3FA8, 0xFF6B4A2F, 175),
  Palette('Berry', 0xFF6A1B7A, 0xFFD0BFFF, 0xFF2F9E44, 250),
];

// ---------------------------------------------------------------------------
// Motifs — each draws a SHADED subject (light / base / dark / outline).
// ---------------------------------------------------------------------------

class Ink {
  const Ink(this.light, this.base, this.dark, this.outline, this.extra);

  final int light, base, dark, outline, extra;
}

typedef Motif = void Function(Zone z, Ink ink);

void _shadeBlob(Zone z, Ink ink) {
  z.g
    ..shade(z.cx - z.scale * 0.34, z.cy - z.scale * 0.34, z.scale * 0.42,
        z.scale * 0.42, ink.base, ink.light)
    ..shade(z.cx + z.scale * 0.30, z.cy + z.scale * 0.34, z.scale * 0.46,
        z.scale * 0.46, ink.base, ink.dark)
    ..outline(ink.base, ink.outline);
}

void mHeart(Zone z, Ink ink) {
  z.fill((x, y) {
    final xx = x * 1.28, yy = -y * 1.28 + 0.12;
    final a = xx * xx + yy * yy - 1;
    return a * a * a - xx * xx * yy * yy * yy <= 0;
  }, ink.base);
  _shadeBlob(z, ink);
}

void mStar(Zone z, Ink ink) {
  final verts = <math.Point<double>>[];
  for (var i = 0; i < 10; i++) {
    final r = i.isEven ? 0.98 : 0.44;
    final a = -math.pi / 2 + i * math.pi / 5;
    verts.add(math.Point(r * math.cos(a), r * math.sin(a) + 0.04));
  }
  z.fill((x, y) {
    var inside = false;
    for (var i = 0, j = verts.length - 1; i < verts.length; j = i++) {
      final a = verts[i], b = verts[j];
      if ((a.y > y) != (b.y > y) &&
          x < (b.x - a.x) * (y - a.y) / (b.y - a.y) + a.x) {
        inside = !inside;
      }
    }
    return inside;
  }, ink.base);
  _shadeBlob(z, ink);
}

void mMoon(Zone z, Ink ink) {
  z.fill((x, y) {
    final d1 = (x + 0.10) * (x + 0.10) + (y - 0.02) * (y - 0.02);
    final d2 = (x - 0.42) * (x - 0.42) + (y + 0.22) * (y + 0.22);
    return d1 <= 0.92 * 0.92 && d2 > 0.78 * 0.78;
  }, ink.base);
  z.fill((x, y) {
    final d1 = (x + 0.10) * (x + 0.10) + (y - 0.02) * (y - 0.02);
    final d2 = (x - 0.42) * (x - 0.42) + (y + 0.22) * (y + 0.22);
    return d1 <= 0.92 * 0.92 && d2 > 0.78 * 0.78 && d2 <= 1.05 * 1.05;
  }, ink.light);
  z.g.outline(ink.base, ink.outline);
}

void mFlower(Zone z, Ink ink) {
  for (var k = 0; k < 6; k++) {
    final ang = k * math.pi / 3;
    final px = 0.56 * math.cos(ang), py = 0.56 * math.sin(ang);
    z.fill((x, y) {
      final dx = x - px, dy = y - py;
      return dx * dx + dy * dy <= 0.37 * 0.37;
    }, ink.base);
  }
  _shadeBlob(z, ink);
  z.fill((x, y) => x * x + y * y <= 0.30 * 0.30, ink.extra);
}

void mBalloon(Zone z, Ink ink) {
  z.fill((x, y) {
    final dy = (y + 0.24) / 1.10;
    return x * x + dy * dy <= 0.54 * 0.54;
  }, ink.base);
  _shadeBlob(z, ink);
  z.fill(
    (x, y) => y > 0.36 && y < 0.88 && (x - math.sin(y * 6) * 0.06).abs() < 0.045,
    ink.outline,
  );
}

void mSun(Zone z, Ink ink) {
  for (var k = 0; k < 8; k++) {
    final a = k * math.pi / 4;
    final px = 0.80 * math.cos(a), py = 0.80 * math.sin(a);
    z.fill((x, y) {
      final dx = x - px, dy = y - py;
      return dx * dx + dy * dy <= 0.17 * 0.17;
    }, ink.extra);
  }
  z.fill((x, y) => x * x + y * y <= 0.56 * 0.56, ink.base);
  _shadeBlob(z, ink);
}

void mDiamond(Zone z, Ink ink) {
  z.fill((x, y) {
    if (y < -0.26) {
      return y >= -0.62 && x.abs() <= 0.66 * (1 - (-y - 0.26) / 0.36 * 0.45);
    }
    return y <= 0.86 && x.abs() <= 0.66 * (1 - (y + 0.26) / 1.12);
  }, ink.base);
  z.fill((x, y) => y >= -0.62 && y < -0.26 && x.abs() < 0.20, ink.light);
  z.fill((x, y) => y > -0.26 && y < 0.86 && x > 0.10 && x < 0.42, ink.dark);
  z.g.outline(ink.base, ink.outline);
}

void mApple(Zone z, Ink ink) {
  z.fill((x, y) {
    final dy = (y - 0.10) / 1.04;
    return x * x + dy * dy <= 0.56 * 0.56;
  }, ink.base);
  _shadeBlob(z, ink);
  z.fill((x, y) => x.abs() < 0.055 && y > -0.82 && y < -0.44, ink.outline);
  z.fill((x, y) {
    final dx = (x - 0.26) / 0.22, dy = (y + 0.70) / 0.12;
    return dx * dx + dy * dy <= 1;
  }, ink.extra);
}

void mGhost(Zone z, Ink ink) {
  z.fill((x, y) {
    if (y < -0.14) {
      final dy = (y + 0.14) / 0.76;
      return x * x + dy * dy * 0.55 <= 0.56 * 0.56;
    }
    if (y > 0.62) return false;
    return x.abs() <= 0.56 && math.sin((x + 1) * 9) * 0.08 + 0.54 > y;
  }, ink.base);
  _shadeBlob(z, ink);
  for (final ex in [-0.21, 0.21]) {
    z.fill((x, y) {
      final dx = x - ex, dy = y + 0.24;
      return dx * dx + dy * dy <= 0.10 * 0.10;
    }, ink.outline);
  }
}

void mTree(Zone z, Ink ink) {
  for (var layer = 0; layer < 3; layer++) {
    final top = -0.86 + layer * 0.38;
    z.fill((x, y) {
      if (y < top || y > top + 0.54) return false;
      final t = (y - top) / 0.54;
      return x.abs() <= 0.30 + t * 0.44 - layer * 0.02;
    }, layer.isEven ? ink.base : ink.dark);
  }
  z.fill((x, y) => y > 0.54 && y < 0.92 && x.abs() < 0.13, ink.extra);
  z.g.outline(ink.base, ink.outline);
}

void mHouse(Zone z, Ink ink) {
  z.fill((x, y) => y > -0.16 && y < 0.74 && x.abs() < 0.62, ink.base);
  z.fill((x, y) {
    if (y < -0.74 || y > -0.16) return false;
    return x.abs() <= 0.76 * ((y + 0.74) / 0.58);
  }, ink.extra);
  z.fill((x, y) => y > 0.10 && y < 0.50 && (x - 0.24).abs() < 0.16, ink.light);
  z.fill((x, y) => y > 0.24 && y < 0.74 && (x + 0.26).abs() < 0.15, ink.dark);
  z.g.outline(ink.base, ink.outline);
}

void mRocket(Zone z, Ink ink) {
  z.fill((x, y) => y >= -0.54 && y <= 0.36 && x.abs() <= 0.27, ink.base);
  z.fill((x, y) {
    if (y < -0.88 || y > -0.50) return false;
    return x.abs() <= 0.29 * ((y + 0.88) / 0.38);
  }, ink.extra);
  z.fill((x, y) {
    if (y < 0.04 || y > 0.46) return false;
    final t = (y - 0.04) / 0.42;
    return x.abs() >= 0.23 && x.abs() <= 0.23 + 0.31 * t;
  }, ink.extra);
  z.fill((x, y) {
    final dy = y + 0.28;
    return x * x + dy * dy <= 0.16 * 0.16;
  }, ink.light);
  z.fill((x, y) {
    if (y < 0.42 || y > 0.84) return false;
    return x.abs() <= 0.18 * (1 - (y - 0.42) / 0.42);
  }, ink.dark);
  z.g.outline(ink.base, ink.outline);
}

void mFish(Zone z, Ink ink) {
  z.fill((x, y) {
    final dx = (x - 0.10) / 0.64, dy = y / 0.44;
    return dx * dx + dy * dy <= 1;
  }, ink.base);
  z.fill(
    (x, y) => x < -0.44 && x > -0.88 && y.abs() < (x + 0.88) * 0.9,
    ink.dark,
  );
  _shadeBlob(z, ink);
  z.fill((x, y) {
    final dx = x - 0.44, dy = y + 0.10;
    return dx * dx + dy * dy <= 0.08 * 0.08;
  }, ink.extra);
}

void mButterfly(Zone z, Ink ink) {
  for (final side in [-1.0, 1.0]) {
    z.fill((x, y) {
      final dx = x - side * 0.40, dy = y + 0.22;
      return dx * dx + dy * dy <= 0.38 * 0.38;
    }, ink.base);
    z.fill((x, y) {
      final dx = x - side * 0.33, dy = y - 0.28;
      return dx * dx + dy * dy <= 0.30 * 0.30;
    }, ink.extra);
  }
  z.g.outline(ink.base, ink.outline);
  z.fill((x, y) => x.abs() < 0.075 && y > -0.56 && y < 0.56, ink.dark);
}

void mMushroom(Zone z, Ink ink) {
  z.fill((x, y) {
    if (y > 0.06 || y < -0.66) return false;
    return x * x + (y + 0.10) * (y + 0.10) * 2.2 <= 0.80;
  }, ink.base);
  z.fill((x, y) => y > 0.06 && y < 0.64 && x.abs() < 0.23, ink.light);
  for (final d in [
    [-0.36, -0.30],
    [0.29, -0.38],
    [0.0, -0.12],
  ]) {
    z.fill((x, y) {
      final dx = x - d[0], dy = y - d[1];
      return dx * dx + dy * dy <= 0.12 * 0.12;
    }, ink.extra);
  }
  z.g.outline(ink.base, ink.outline);
}

void mCat(Zone z, Ink ink) {
  z.fill((x, y) {
    final dy = (y - 0.10) / 0.86;
    return x * x + dy * dy <= 0.58 * 0.58;
  }, ink.base);
  for (final side in [-1.0, 1.0]) {
    z.fill((x, y) {
      if (y > -0.34 || y < -0.86) return false;
      final t = (y + 0.86) / 0.52;
      return (x - side * 0.36).abs() <= 0.22 * t;
    }, ink.base);
  }
  _shadeBlob(z, ink);
  for (final ex in [-0.22, 0.22]) {
    z.fill((x, y) {
      final dx = x - ex, dy = y - 0.02;
      return dx * dx + dy * dy <= 0.10 * 0.10;
    }, ink.extra);
  }
}

void mCrown(Zone z, Ink ink) {
  z.fill((x, y) => y > 0.06 && y < 0.60 && x.abs() < 0.72, ink.base);
  for (final px in [-0.56, 0.0, 0.56]) {
    z.fill((x, y) {
      if (y < -0.62 || y > 0.10) return false;
      return (x - px).abs() <= 0.22 * ((y + 0.62) / 0.72);
    }, ink.base);
  }
  _shadeBlob(z, ink);
  for (final px in [-0.40, 0.0, 0.40]) {
    z.fill((x, y) {
      final dx = x - px, dy = y - 0.30;
      return dx * dx + dy * dy <= 0.10 * 0.10;
    }, ink.extra);
  }
}

class MotifDef {
  const MotifDef(this.name, this.draw, this.tier);

  final String name;
  final Motif draw;
  final int tier;
}

const motifs = [
  MotifDef('Heart', mHeart, 0),
  MotifDef('Star', mStar, 0),
  MotifDef('Balloon', mBalloon, 0),
  MotifDef('Sun', mSun, 0),
  MotifDef('Apple', mApple, 0),
  MotifDef('Diamond', mDiamond, 0),
  MotifDef('Moon', mMoon, 1),
  MotifDef('Bloom', mFlower, 1),
  MotifDef('Ghost', mGhost, 1),
  MotifDef('Pine', mTree, 1),
  MotifDef('Shroom', mMushroom, 1),
  MotifDef('Crown', mCrown, 1),
  MotifDef('House', mHouse, 2),
  MotifDef('Rocket', mRocket, 2),
  MotifDef('Fish', mFish, 2),
  MotifDef('Flutter', mButterfly, 2),
  MotifDef('Kitty', mCat, 2),
];

// ---------------------------------------------------------------------------
// Scene composition
// ---------------------------------------------------------------------------

class Scene {
  Scene(this.grid, this.name, this.colorCount);

  final Grid grid;
  final String name;
  final int colorCount;
}

Scene buildScene(LevelSpec spec, {required int seed}) {
  final rnd = math.Random(seed);
  final n = spec.gridSize;
  final pal = palettes[rnd.nextInt(palettes.length)];
  final accents = List<int>.from(pal.accents)..shuffle(rnd);
  final g = Grid(n, pal.skyLow);

  // 1. GRADED SKY — horizontal bands from deep top to bright horizon. Every
  //    column crosses each band, so this alone creates vertical churn.
  // Only two bands: the quantizer merges anything closer than ~52 in
  // perceptual distance, so intermediate gradient steps would vanish.
  final horizon = -0.25 + (rnd.nextDouble() - 0.5) * 0.35;
  g.fill((x, y) => y < horizon, pal.skyTop);
  g.fill((x, y) => y >= horizon, pal.skyLow);

  // 2. GROUND — two tones plus a speckled seam.
  final hasGround = rnd.nextDouble() < 0.55;
  if (hasGround) {
    final groundTop = 0.52 + rnd.nextDouble() * 0.16;
    g.fill((x, y) => y > groundTop, pal.ground);
    g.fill((x, y) => y > groundTop + 0.18, darken(pal.ground, 0.58));
    final seamY = ((groundTop + 1) / 2 * n).floor().clamp(0, n - 1);
    for (var x = 0; x < n; x++) {
      if (rnd.nextDouble() < 0.45) g.set(x, seamY, lighten(pal.ground, 0.55));
    }
  }

  // 3. BACKDROP SCENERY — distant hills behind the subject.
  if (rnd.nextBool()) {
    final hill = accents[6 % accents.length];
    final hy = hasGround ? 0.46 : 0.62;
    for (final hx in [-0.55, 0.15, 0.75]) {
      g.fill((x, y) {
        final dx = (x - hx) / 0.52, dy = (y - hy) / 0.42;
        return dx * dx + dy * dy <= 1 && y < hy;
      }, hill);
    }
  }

  // 4. MAIN MOTIF — shaded light/base/dark/outline plus an accent detail.
  final pool = motifs.where((m) => m.tier <= spec.tier).toList();
  final motif = pool[rnd.nextInt(pool.length)];
  final base = accents[0];
  final ink = Ink(
    lighten(base, 0.55),
    base,
    darken(base, 0.58),
    darken(base, 0.32),
    accents[1],
  );
  final zone = Zone(
    g,
    cy: hasGround ? -0.12 : 0.0,
    scale: 0.58 + spec.t * 0.16,
  );
  motif.draw(zone, ink);

  // 5. SECONDARY MOTIFS — at other heights, so columns cross several
  //    subjects on the way down.
  final minis = spec.hard ? 2 : (spec.t > 0.45 ? 1 : 0);
  for (var k = 0; k < minis; k++) {
    final mini = pool[rnd.nextInt(pool.length)];
    final mBase = accents[(2 + k) % accents.length];
    mini.draw(
      Zone(g, cx: k.isEven ? -0.62 : 0.64, cy: -0.58 + k * 0.16, scale: 0.20),
      Ink(
        lighten(mBase, 0.55),
        mBase,
        darken(mBase, 0.58),
        darken(mBase, 0.32),
        accents[(4 + k) % accents.length],
      ),
    );
  }

  // 6. HARD STRUCTURES — frames gate the bottom rows and checker bands
  //    force alternating colors as the drain reaches them.
  if (spec.hard) {
    g.ring(0, accents[3 % accents.length]);
    if (n >= 24) g.ring(1, accents[4 % accents.length]);
    if (n >= 32) g.ring(2, accents[5 % accents.length]);
    final rowsToCheck = (1 + spec.t * 2).round();
    for (var k = 0; k < rowsToCheck; k++) {
      final y = n - 3 - k * 2;
      if (y > 2) {
        g.checkerRow(
          y,
          accents[(6 + k) % accents.length],
          accents[(7 + k) % accents.length],
          period: 1 + k,
        );
      }
    }
  }

  // 7. BACKGROUND BANDING — the difficulty dial, applied as DESIGN, not
  //    noise: only sky/ground cells are re-tinted, in horizontal bands, so
  //    the subject stays crisp while every column crosses many colors.
  final bgColors = <int>{pal.skyTop, pal.skyLow, pal.ground,
      darken(pal.ground, 0.58), lighten(pal.ground, 0.55)};
  final bandPalette = <int>[
    pal.skyTop,
    pal.skyLow,
    accents[3 % accents.length],
    accents[4 % accents.length],
  ];
  _bandBackground(g, bgColors, bandPalette, spec.churn, rnd);

  // 8. SPARKLE DETAIL — only on open background, so the subject stays
  //    crisp instead of getting speckled.
  final sparkles = 2 + rnd.nextInt(2) + (n ~/ 14);
  final bandColors = {
    pal.skyTop,
    pal.skyLow,
    accents[3 % accents.length],
    accents[4 % accents.length],
  };
  for (var s = 0; s < sparkles; s++) {
    for (var attempt = 0; attempt < 30; attempt++) {
      final x = 2 + rnd.nextInt(n - 4), y = 2 + rnd.nextInt(n - 4);
      var clear = true;
      for (var dy = -1; dy <= 1 && clear; dy++) {
        for (var dx = -1; dx <= 1 && clear; dx++) {
          if (!bandColors.contains(g.at(x + dx, y + dy))) clear = false;
        }
      }
      if (!clear) continue;
      g.plus(x, y, accents[(s + 2) % accents.length], arm: n >= 20 ? 1 : 0);
      break;
    }
  }

  // 9. FAIRNESS PASS — merge anything the quantizer would merge anyway,
  //    cap the palette, top back up to the target with well-separated
  //    accents, then make sure no color is a slot hostage.
  final area = n * n;
  final cap = spec.colorTarget.clamp(5, (5 + area ~/ 90).clamp(5, 12));
  _enforceSeparation(g, 58);
  _capColors(g, cap);
  _topUpColors(g, accents, cap, rnd);
  // Bottom-drain fairness is about COLUMN COVERAGE, not raw cell counts: a
  // color living in only a few columns leaves its bottle starving in a
  // slot while the rest of the board drains. Spread every color across
  // enough columns that its bottle keeps finding work.
  _ensureColumnCoverage(g, 0.55, rnd);


  return Scene(g, motif.name, _tally(g).length);
}

Map<int, int> _tally(Grid g) {
  final counts = <int, int>{};
  for (final c in g.cells) {
    counts[c] = (counts[c] ?? 0) + 1;
  }
  return counts;
}

double _colorDist(int c1, int c2) {
  final dr = ((c1 >> 16 & 0xFF) - (c2 >> 16 & 0xFF)).toDouble();
  final dg = ((c1 >> 8 & 0xFF) - (c2 >> 8 & 0xFF)).toDouble();
  final db = ((c1 & 0xFF) - (c2 & 0xFF)).toDouble();
  return math.sqrt(0.3 * dr * dr + 0.59 * dg * dg + 0.11 * db * db);
}

/// Fraction of vertical neighbour pairs whose color differs.
double gridChurn(Grid g) {
  var changes = 0, pairs = 0;
  for (var x = 0; x < g.n; x++) {
    for (var y = 0; y < g.n - 1; y++) {
      pairs++;
      if (g.at(x, y) != g.at(x, y + 1)) changes++;
    }
  }
  return pairs == 0 ? 0 : changes / pairs;
}

/// Re-tints ONLY background cells (sky/ground) in horizontal bands, at the
/// band period whose resulting vertical churn lands closest to [target].
/// This is what makes late levels hard to drain — every column crosses
/// many colors — while keeping the picture a designed scene rather than
/// static.
void _bandBackground(
  Grid g,
  Set<int> bgColors,
  List<int> bandPalette,
  double target,
  math.Random rnd,
) {
  final original = List<int>.from(g.cells);
  final isBg = [for (final c in original) bgColors.contains(c)];

  List<int> applied(int period, int palLen) {
    final out = List<int>.from(original);
    for (var y = 0; y < g.n; y++) {
      final color = bandPalette[(y ~/ period) % palLen];
      for (var x = 0; x < g.n; x++) {
        final i = y * g.n + x;
        if (isBg[i]) out[i] = color;
      }
    }
    return out;
  }

  var bestCells = original;
  var bestErr = double.infinity;
  for (final period in [1, 2, 3, 4]) {
    for (final palLen in [2, 3, 4]) {
      if (palLen > bandPalette.length) continue;
      final cells = applied(period, palLen);
      g.cells.setAll(0, cells);
      final err = (gridChurn(g) - target).abs();
      if (err < bestErr) {
        bestErr = err;
        bestCells = cells;
      }
    }
  }
  g.cells.setAll(0, bestCells);
}

/// Stamps cells so every color appears in at least [minFraction]/// Stamps cells so every color appears in at least [minFraction] of the
/// columns — the single most important fairness rule for bottom-drain,
/// since a color confined to a few columns starves its bottle.
void _ensureColumnCoverage(Grid g, double minFraction, math.Random rnd) {
  final needColumns = (g.n * minFraction).ceil();
  for (final color in _tally(g).keys.toList()) {
    final present = <int>{};
    for (var x = 0; x < g.n; x++) {
      for (var y = 0; y < g.n; y++) {
        if (g.at(x, y) == color) {
          present.add(x);
          break;
        }
      }
    }
    if (present.length >= needColumns) continue;
    final missing = [
      for (var x = 0; x < g.n; x++)
        if (!present.contains(x)) x,
    ]..shuffle(rnd);
    var toAdd = needColumns - present.length;
    for (final x in missing) {
      if (toAdd <= 0) break;
      // Overwrite a cell of whichever color can spare it most.
      final counts = _tally(g);
      var bestY = -1, bestCount = 0;
      for (var y = 0; y < g.n; y++) {
        final c = counts[g.at(x, y)] ?? 0;
        if (g.at(x, y) != color && c > bestCount) {
          bestCount = c;
          bestY = y;
        }
      }
      if (bestY >= 0) {
        g.set(x, bestY, color);
        toAdd--;
      }
    }
  }
}

/// Merges any pair closer than [minDist] so the runtime quantizer (which
/// merges below ~52) cannot silently collapse the palette under 5.
void _enforceSeparation(Grid g, double minDist) {
  while (true) {
    final counts = _tally(g);
    final colors = counts.keys.toList();
    var mergedAny = false;
    for (var i = 0; i < colors.length && !mergedAny; i++) {
      for (var j = i + 1; j < colors.length; j++) {
        if (_colorDist(colors[i], colors[j]) >= minDist) continue;
        // Keep the more common one.
        final keep =
            counts[colors[i]]! >= counts[colors[j]]! ? colors[i] : colors[j];
        final drop = keep == colors[i] ? colors[j] : colors[i];
        for (var k = 0; k < g.cells.length; k++) {
          if (g.cells[k] == drop) g.cells[k] = keep;
        }
        mergedAny = true;
        break;
      }
    }
    if (!mergedAny) return;
  }
}

/// Adds accent blocks (well separated by construction) until the scene has
/// [target] distinct colors — the campaign's 5-color floor is a hard rule.
void _topUpColors(Grid g, List<int> accents, int target, math.Random rnd) {
  for (final accent in accents) {
    var counts = _tally(g);
    if (counts.length >= target) return;
    if (counts.keys.any((c) => _colorDist(c, accent) < 58)) continue;
    // Stamp a readable patch so the new color is never a slot hostage.
    final need = math.max(10, g.n * g.n ~/ 60);
    var placed = 0, guard = 0;
    while (placed < need && guard++ < 2000) {
      final x = rnd.nextInt(g.n), y = rnd.nextInt(g.n);
      counts = _tally(g);
      if ((counts[g.at(x, y)] ?? 0) > need) {
        g.set(x, y, accent);
        placed++;
      }
    }
  }
}

/// Merges the rarest colors into their nearest kept color until at most
/// [target] distinct colors remain.
void _capColors(Grid g, int target) {
  var counts = _tally(g);
  while (counts.length > target) {
    final rarest =
        counts.entries.reduce((a, b) => a.value <= b.value ? a : b).key;
    var best = rarest;
    var bestD = double.infinity;
    for (final c in counts.keys) {
      if (c == rarest) continue;
      final d = _colorDist(c, rarest);
      if (d < bestD) {
        bestD = d;
        best = c;
      }
    }
    for (var i = 0; i < g.cells.length; i++) {
      if (g.cells[i] == rarest) g.cells[i] = best;
    }
    counts = _tally(g);
  }
}
